spring:
  datasource:
    url: jdbc:postgresql://judy:5432/demo_db
    username: username
    password: ameda
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
  application:
    name: spring-boot-postgresql

#When container to container are communicating, then it's crucial to have container-name as host
#i.e jdbc:postgresql://judy:5430/demo_db